homepage
frontend-id/feid.dev pull request #4
Opened 2020-09-16 12:10 UTC by pveyes

Resolve #3

2020-09-16 12:20 UTC, grikomsn commented
Looks beautiful! ❤

2020-09-16 12:46 UTC, grikomsn commented
#### 📝Changed routes:


| [**/**](https://feid-dev-git-homepage.frontend-id.vercel.app/) |
|:-:|
|<a href="https://feid-dev-git-homepage.frontend-id.vercel.app/"><img src="https://images.weserv.nl?url=https://s.microlink.io/prt80HkdsuaT2ggWBXE6ikHkfaw_.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/80_CiezvrTIBLnc0BxWlcnDFARE_.png">(view full size)</a> |







Commit 636649062693664b2879dee224bd6c1870e3fa03 (https://feid-dev-git-homepage.frontend-id.vercel.app).

2020-09-16 16:21 UTC, jefrydco approved these changes

2020-09-17 06:20 UTC, resir014 requested changes

2020-09-17 06:20 UTC, resir014 commented on src/components/Header.tsx
> +        <Link href="https://twitter.com/feid.dev" isExternal>
```suggestion
        <Link href="https://twitter.com/feid_dev" isExternal>
```

Twitter account is @feid_dev

2020-09-17 06:20 UTC, resir014 commented on src/pages/index.tsx
> +            Frontend ID adalah sebuah komunitas teknologi untuk para pengembang antar muka di
```suggestion
            Frontend Indonesia adalah sebuah komunitas teknologi untuk para pengembang antar muka di
```

Frontend ID -> Frontend Indonesia

2020-09-17 06:20 UTC, resir014 commented on src/pages/index.tsx
> +              title="Frontend ID Discord"
```suggestion
              title="Frontend Indonesia Discord"
```

idem.

2020-09-17 06:20 UTC, resir014 commented on src/pages/index.tsx
> +                    Join Frontend ID
```suggestion
                    Join Frontend Indonesia
```

idem.

2020-09-17 06:20 UTC, resir014 commented on src/pages/index.tsx
> +        <Text>Copyright &copy; {new Date().getFullYear()} Frontend ID</Text>
```suggestion
        <Text>Copyright &copy; {new Date().getFullYear()} Frontend Indonesia</Text>
```

2020-09-17 07:43 UTC, jefrydco commented
Btw baru ingat, perlu i18n sepertinya, gimana menurut teman-teman?

2020-09-17 09:47 UTC, resir014 commented
> Btw baru ingat, perlu i18n sepertinya, gimana menurut teman-teman?

@jefrydco Mungkin kita tunggu sampe RFC buat [native i18n routes](https://twitter.com/timneutkens/status/1305495797224611840) diimplementasikan di Next.js dulu. 😅 

Kalau sekarang sih, mungkin bisa kita set atribut `lang="id"` dulu di tag `<html>`. Bisa kita taruh di *page* `_document.tsx` kalau di Next.js.

2020-09-17 14:39 UTC, pveyes commented
force pushed to rebase & sign commit

2020-09-18 03:03 UTC, resir014 approved these changes

2020-09-18 03:07 UTC, resir014 commented
![image](https://user-images.githubusercontent.com/5663877/93550879-a19c3100-f996-11ea-958a-70bb27d4c5f1.png)

Hmm, teks Angular-nya jadi "kedorong" ke bawah setelah diganti namanya jadi Frontend Indonesia. Mungkin diubah copy-nya sedikit biar gak "kedorong" kebawah at least di desktop? 🤔

2020-09-18 03:12 UTC, jefrydco commented
Mungkin bisa 

`teknologi untuk pengembang antar muka di Indonesia`

paranya dihilangkan

2020-09-18 08:07 UTC, pveyes commented
> ![image](https://user-images.githubusercontent.com/5663877/93550879-a19c3100-f996-11ea-958a-70bb27d4c5f1.png)
> 
> Hmm, teks Angular-nya jadi "kedorong" ke bawah setelah diganti namanya jadi Frontend Indonesia. Mungkin diubah copy-nya sedikit biar gak "kedorong" kebawah at least di desktop? 🤔

Itu karena behavior svg icon nya inline-block jadi ke push, mungkin bisa gw wrap jadi 1 element inline-block jadi icon + text selalu ada di 1 line



> Mungkin bisa
> 
> `teknologi untuk pengembang antar muka di Indonesia`
> 
> paranya dihilangkan

sip 👍

2020-09-18 08:12 UTC, resir014 commented
oke sip! LGTM for now.

2020-09-18 10:03 UTC, pveyes commented
somehow prettier nya gak jalan waktu commit mungkin ada salah config gw track di https://github.com/frontend-id/feid.dev/issues/5

2020-09-21 00:39 UTC, merged